// produce Activities from system state, or the Services the views read; may use Amane services
// and Island::write()

pub mod audio;
pub mod battery;
pub mod bluetooth;
pub mod bus;
pub mod caffeine;
pub mod calendar;
pub mod capture;
pub mod clipboard;
pub mod google;
pub mod icons;
pub mod json;
pub mod launch;
pub mod media;
pub mod network;
pub mod niri;
pub mod notifications;
pub mod osd;
pub mod pipewire;
pub mod playback;
pub mod power;
pub mod privacy;
pub mod recording;
pub mod system;
pub mod timer;
pub mod tray;
pub mod wake;
pub mod wallpaper;
pub mod wifi;
pub mod windows;
pub mod workspace;
